# Java Properties
target_java_version=25

# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 1.1.3+26.1
target_minecraft_version = 26.1
maven_group = thomilist
archives_base_name = showdurability

# Dependencies
fabric_api_version=0.148.2+26.1.2
gson_version=2.14.0
